# Generated by Django 4.1.4 on 2023-01-29 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_goods_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2023, 1, 29))),
                ('text', models.TextField(max_length=200)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goods')),
            ],
        ),
    ]
